version: '3.0'

networks:
  hackribeirao:
    driver: bridge

services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6606:6606"
    networks:
      - hackribeirao
    env_file:
      - ./flask.env
    depends_on:
      - postgres
  postgres:
    build:
      context: ./postgres_docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    networks:
      - hackribeirao